---
# tasks file for aws-monitoring-scripts


- name: Variables for OS
  include_vars: "{{ ansible_os_family }}.yml"

- name: Exit if no keys defined
  fail: 
    msg: "You will need to define keys to continue"
  when: aws_secret_key is none or aws_access_key is none

- name: Ubuntu/Debian | Installing required packages
  package: 
    name: "{{ item }}"
    state: present
  with_items:
      - unzip
      - libdatetime-perl
      - libwww-perl
  when: ansible_distribution == "Ubuntu" or ansible_distribution == "Debian"

- name: RedHat | Installing required packages    
  package: 
    name: "{{ item }}"
    state: present
  with_items:
    - zip
    - unzip
    - perl-Sys-Syslog     
    - perl-DateTime
    - perl-LWP-Protocol-https
    - perl-Digest-SHA
  when: ansible_distribution == "RedHat" 

- name: Downloading and installing CloudWatch monitoring scripts
  unarchive:
     src: https://aws-cloudwatch.s3.amazonaws.com/downloads/CloudWatchMonitoringScripts-{{ aws_monitoring_version }}.zip
     dest: "{{ aws_monitoring_base_install }}"
     owner: "{{ aws_monitoring_user }}"
     remote_src: yes

- name: Adding AWS Credentials
  template:
     src: awscreds.conf.j2
     dest: "{{ aws_monitoring_base_install }}/aws-scripts-mon/awscreds.conf"
     owner: "{{ aws_monitoring_user }}"
     mode: 0400

- name: Adding a Cron job for scripts
  cron:
     name: "aws_monitoring"
     user: "{{ aws_monitoring_user }}"
     minute: "*/5"
     job: "{{aws_monitoring_base_install}}/aws-scripts-mon/mon-put-instance-data.pl -from-cron {{ aws_monitoring_parameters }}"

- include_tasks: motd.yml
     
